# Use root/example as user/password credentials
version: '3.1'

services:
  app:
    container_name: app
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      target: production
    # image: loic08/sbcdrink-app:main
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ../:/app