version: '3.1'

services:
  sbcdrink-app:
    container_name: sbcdrink-app
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      # target: development
      target: production
    # image: loic08/sbcdrink-app:main
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ../:/app